# 当有改动推送到master分支时，启动Action
name: 同步 Gitee 图床

on:
  push:
    branches:
      - master #2020年10月后github新建仓库默认分支改为main，注意更改

  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: master #2020年10月后github新建仓库默认分支改为main，注意更改

    - name: 配置Git用户名邮箱
      run: |
        git config --global user.name "Vicosna"
        git config --global user.email "ihohintsui@gmail.com"

    - name: 同步至 Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在github私有仓库的Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:vicosna/PicBed.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:vicosna/PicBed.git"
